# Generated by Django 5.1.2 on 2024-11-12 20:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_delete_reservation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserved_at', models.DateTimeField(default=django.utils.timezone.now, help_text='The date and time the reservation is made')),
                ('reservation_time', models.DateTimeField(help_text='The date and time the reservation is for')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Optional notes or special instructions for the reservation', null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_reservations', to='accounts.studentprofile')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_reservations', to='accounts.teacherprofile')),
            ],
            options={
                'ordering': ['reservation_time'],
                'unique_together': {('student', 'reservation_time')},
            },
        ),
    ]
