# Generated by Django 5.1.2 on 2024-11-03 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_user_type_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='teacher_type',
            field=models.CharField(choices=[('math', 'Mathematics'), ('piano', 'Piano'), ('music', 'Music'), ('english', 'English'), ('swimming', 'Swimming'), ('billiard', 'Billiard'), ('sing', 'Sing'), ('boxing', 'Boxing')], default=1),
            preserve_default=False,
        ),
    ]
