# Generated by Django 5.1.2 on 2024-11-13 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_delete_reservation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherprofile',
            name='rating',
        ),
    ]
