# Generated by Django 5.1.2 on 2024-11-03 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_teacher_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='teacher_type',
            field=models.CharField(choices=[('math', 'Mathematics'), ('piano', 'Piano'), ('music', 'Music'), ('english', 'English'), ('swimming', 'Swimming'), ('billiard', 'Billiard'), ('sing', 'Sing'), ('boxing', 'Boxing'), ('other', 'Other')], default='other'),
        ),
    ]
