# Generated by Django 5.1.2 on 2024-11-03 19:53

import SuperTeacher.accounts.validations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/', validators=[SuperTeacher.accounts.validations.validate_file_size]),
        ),
    ]
